name: Build Windows EXE (Nuitka + UPX)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    paths:
      - '**/*.py'
      - 'requirements.txt'
      - '.github/workflows/windows-nuitka.yml'

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nuitka zstandard

      - name: Install UPX
        run: choco install upx -y

      - name: Build EXE (standalone)
        run: |
          python -m nuitka --standalone --enable-plugin=pyside6 --include-data-dir=static=static --include-data-dir=templates=templates --include-data-files=quotes.json=quotes.json --include-data-files=quotes.default.json=quotes.default.json --output-dir=build/windows/allinone --remove-output --upx all_in_one.py

      - name: Zip distribution
        run: |
          Compress-Archive -Path build/windows/allinone/all_in_one.dist/* -DestinationPath build/windows/allinone/landing-judge-windows.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: landing-judge-windows
          path: build/windows/allinone/landing-judge-windows.zip

      - name: Publish GitHub Release (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: build/windows/allinone/landing-judge-windows.zip
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          body: |
            Automated Windows build using Nuitka + UPX.
            Includes data directories (static, templates) and quotes files.
            See README for usage and UI features.